bash only

diff --git a/pkg-src/DEBIAN/postinst b/pkg-src/DEBIAN/postinst
--- a/pkg-src/DEBIAN/postinst
+++ b/pkg-src/DEBIAN/postinst
@@ -1,8 +1,6 @@
-#!/bin/sh
-
+#!/bin/env sh
 set -e
 
-pip3 install {{python-packages}}
 sudo systemctl daemon-reload
-systemctl start raspi-fan-control || echo "Can't start service"
-systemctl enable raspi-fan-control || echo "Can't enable service"
+systemctl start cooler || echo "Can't start service"
+systemctl enable cooler || echo "Can't enable service"
diff --git a/pkg-src/DEBIAN/prerm b/pkg-src/DEBIAN/prerm
--- a/pkg-src/DEBIAN/prerm
+++ b/pkg-src/DEBIAN/prerm
@@ -1,6 +1,5 @@
-#!/bin/sh
-
+#!/bin/env sh
 set -e
 
-systemctl disable raspi-fan-control || echo "Can't disable service"
-systemctl stop raspi-fan-control || echo "Can't stop service"
+systemctl disable cooler || echo "Can't disable service"
+systemctl stop cooler || echo "Can't stop service"
